export * from "./generated/api";
export type {
  AnswerQuestionBody,
  AudioUploadResponse,
  ChatBody,
  ChatResponse,
  CreateLectureBody,
  CreateQuestionBody,
  ExtractedTask,
  GetLecturesParams,
  GetMeParams,
  GetQuestionsParams,
  GetTasksParams,
  GetUploadUrlBody,
  HealthStatus,
  Lecture,
  LectureDetail,
  LectureDetailStatus,
  LectureStatus,
  ProcessLectureBody,
  ProcessLectureResponse,
  Question,
  SummarizeBody,
  SummarizeResponse,
  SyncUserBody,
  SyncUserBodyRole,
  Task,
  TaskStatus,
  TranscribeBody,
  TranscribeResponse,
  UploadLectureAudioBody,
  UploadUrlResponse,
  User,
  UserRole,
} from "./generated/types";
